apiVersion: v1
data:
  SERVE_PORT: "8080"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hello
  template:
    metadata:
      labels:
        name: hello
    spec:
      containers:
      - name: hello
        image: moazrefat/hello:hf
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: hello
        envFrom:
          - configMapRef:
              name: config
---
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: hello
  type: LoadBalancer